### ISSUE TITLE
Error while deploying on vercel

### ISSUE THREAD

**Issue by PrakharDoneria** [alii13/whatsapp-clone#15]
`
[15:01:19] Running build in Washington, D.C., USA (East) – iad1
[15:01:20] Cloning github.com/PrakharDoneria/whatsapp-clone (Branch: master, Commit: be9f12e)
[15:01:20] Cloning completed: 446.042ms
[15:01:20] Previous build cache not available
[15:01:20] Running "vercel build"
[15:01:21] Vercel CLI 33.0.1
[15:01:22] Installing dependencies...
[15:01:25] npm WARN old lockfile 
[15:01:25] npm WARN old lockfile The package-lock.json file was created with an old version of npm,
[15:01:25] npm WARN old lockfile so supplemental metadata must be fetched from the registry.
[15:01:25] npm WARN old lockfile 
[15:01:25] npm WARN old lockfile This is a one-time fix-up, please be patient...
[15:01:25] npm WARN old lockfile 
[15:01:53] npm WARN deprecated w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
[15:01:53] npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
[15:01:54] npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
[15:01:54] npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
[15:01:54] npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
[15:01:54] npm WARN deprecated source-map-url@0.4.0: See https://github.com/lydell/source-map-url#deprecated
[15:01:54] npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
[15:01:54] npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[15:01:55] npm WARN deprecated sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
[15:01:55] npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
[15:01:56] npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
[15:01:56] npm WARN deprecated mini-create-react-context@0.4.0: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
[15:01:56] npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
[15:01:57] npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
[15:01:57] npm WARN deprecated har-validator@5.1.5: this library is no longer supported
[15:01:58] npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
[15:01:58] npm WARN deprecated figgy-pudding@3.5.2: This module is no longer supported.
[15:01:58] npm WARN deprecated html-webpack-plugin@4.0.0-beta.11: please switch to a stable version
[15:01:58] npm WARN deprecated domexception@1.0.1: Use your platform's native DOMException instead
[15:01:58] npm WARN deprecated eslint-loader@3.0.3: This loader has been deprecated. Please use eslint-webpack-plugin
[15:01:59] npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
[15:02:00] npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
[15:02:00] npm WARN deprecated abab@2.0.4: Use your platform's native atob() and btoa() methods instead
[15:02:00] npm WARN deprecated babel-eslint@10.1.0: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
[15:02:00] npm WARN deprecated @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
[15:02:00] npm WARN deprecated @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
[15:02:01] npm WARN deprecated @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
[15:02:01] npm WARN deprecated @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
[15:02:01] npm WARN deprecated @babel/plugin-proposal-private-methods@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-private-methods instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.11.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-logical-assignment-operators@7.11.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-logical-assignment-operators instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-json-strings@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-export-namespace-from@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-export-namespace-from instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-dynamic-import@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.10.5: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-class-properties@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-unicode-property-regex@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.11.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
[15:02:01] npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.10.4: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
[15:02:02] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[15:02:02] npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
[15:02:03] npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
[15:02:03] npm WARN deprecated @hapi/joi@15.1.1: Switch to 'npm install joi'
[15:02:03] npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
[15:02:04] npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
[15:02:04] npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.9.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
[15:02:04] npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
[15:02:04] npm WARN deprecated @babel/plugin-proposal-class-properties@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
[15:02:04] npm WARN deprecated @material-ui/system@4.9.14: You can now upgrade to @mui/system. See the guide: https://mui.com/guides/migration-v4/
[15:02:06] npm WARN deprecated @material-ui/styles@4.10.0: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
[15:02:08] npm WARN deprecated core-js-pure@3.6.5: core-js-pure@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js-pure.
[15:02:08] npm WARN deprecated core-js@3.6.5: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[15:02:08] npm WARN deprecated core-js@2.6.11: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
[15:02:09] npm WARN deprecated @material-ui/core@4.11.0: Material UI v4 doesn't receive active development since September 2021. See the guide https://mui.com/material-ui/migration/migration-v4/ to upgrade to v5.
[15:02:11] npm WARN deprecated @material-ui/icons@4.9.1: You can now upgrade to @mui/icons. See the guide: https://mui.com/guides/migration-v4/
[15:02:12] 
[15:02:12] added 1745 packages in 49s
[15:02:12] 
[15:02:12] 71 packages are looking for funding
[15:02:12]   run `npm fund` for details
[15:02:12] npm notice 
[15:02:12] npm notice New major version of npm available! 9.8.1 -> 10.2.5
[15:02:12] npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.2.5>
[15:02:12] npm notice Run `npm install -g npm@10.2.5` to update!
[15:02:12] npm notice 
[15:02:12] Detected `package-lock.json` generated by npm 7+
[15:02:12] Running "npm run build"
[15:02:13] 
[15:02:13] > whatsapp@0.1.0 build
[15:02:13] > react-scripts build
[15:02:13] 
[15:02:14] Creating an optimized production build...
[15:02:14] Error: error:0308010C:digital envelope routines::unsupported
[15:02:14]     at new Hash (node:internal/crypto/hash:69:19)
[15:02:14]     at Object.createHash (node:crypto:133:10)
[15:02:14]     at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
[15:02:14]     at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
[15:02:14]     at handleParseError (/vercel/path0/node_modules/webpack/lib/NormalModule.js:471:10)
[15:02:14]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:503:5
[15:02:14]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:358:12
[15:02:14]     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[15:02:14]     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[15:02:14]     at iterateNormalLoaders (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[15:02:15] /vercel/path0/node_modules/react-scripts/scripts/build.js:19
[15:02:15]   throw err;
[15:02:15]   ^
[15:02:15] 
[15:02:15] Error: error:0308010C:digital envelope routines::unsupported
[15:02:15]     at new Hash (node:internal/crypto/hash:69:19)
[15:02:15]     at Object.createHash (node:crypto:133:10)
[15:02:15]     at module.exports (/vercel/path0/node_modules/webpack/lib/util/createHash.js:135:53)
[15:02:15]     at NormalModule._initBuildHash (/vercel/path0/node_modules/webpack/lib/NormalModule.js:417:16)
[15:02:15]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:452:10
[15:02:15]     at /vercel/path0/node_modules/webpack/lib/NormalModule.js:323:13
[15:02:15]     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:367:11
[15:02:15]     at /vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:233:18
[15:02:15]     at context.callback (/vercel/path0/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[15:02:15]     at /vercel/path0/node_modules/babel-loader/lib/index.js:59:103 {
[15:02:15]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[15:02:15]   library: 'digital envelope routines',
[15:02:15]   reason: 'unsupported',
[15:02:15]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[15:02:15] ▲ System message: 💡 The "unsupported digital envelope" problem may be resolved by adding `NODE_OPTIONS=--openssl-legacy-provider` to your env vars
[15:02:15] }
[15:02:15] 
[15:02:15] Node.js v18.18.2
[15:02:15] Error: Command "npm run build" exited with 1
[15:02:15] 
[15:02:16] ▲ System message: 💡 The "unsupported digital envelope" problem may be resolved by adding `NODE_OPTIONS=--openssl-legacy-provider` to your env vars
`

**Comment by alii13** [comment]
Can you add a description of the error? Issue lacks context

**Comment by PrakharDoneria** [comment]
Soory but that what I got from vercel i forked it and added my credentials that's all and tried to host it. You can try reproducing it by doing this method
